### PR TITLE
Enable configuration with include/exclude patterns

### PR DESCRIPTION
**Pull request by ascheman**
Contributes to jQAssistant/jqa-yaml2-plugin#10

### CODE REVIEW

**Comment by obfischer** [comment]
Could you please document this feature in the documentation of the plugin?

**Review by obfischer — CHANGES_REQUESTED** [review]
Could you please document how the inclusion/exclusion works in the documentation of the plugin?

**Comment by ascheman** [comment]
Where would you like to see the documentation? I see the following opportunities:
* As part of the release notes?
* Add an index.adoc to the impl.scanner package and include to YMLFileScannerPlugin with respective tags (similar to the .adoc files in api.model)?
* As part of the scanner.adoc (which is nearly empty btw.)?
* Any other location in the source code?

BTW: If the index.adoc is the root of the user documentation it would be great to find it in a more prominent place (I did not even see it until you raised your PR comment here).

**Comment by obfischer** [comment]
Hi @ascheman,
we are changing the structure of our documentation. The entry point for the documentation, the new one, is at `src/main/java/com/buschmais/jqassistant/plugin/yaml2/api/model/index.adoc`.

**Comment by ascheman** [comment]
Thanks, @obfischer, I have added some documenation (in alignment with the jqa-json-plugin). I hope this matches your expectations?

**Review by obfischer — APPROVED** [review]

**Comment by obfischer** [comment]
Hi @ascheman, will it help you if we provide a milestone release with your enhancement?

**Comment by ascheman** [comment]
Thank you, @obfischer, it will help but probably not yet. I have to prepare some more things until I will go public with my current customer for this approach, e.g., I will have to extend my own [jQA Ansible Plugin](https://github.com/ascheman/jqa-ansible-plugin). When everything is settled so far, a milestone release would be great. For the time being I will come back to you, @DirkMahler and probably others with some questions (on the Google Group/Mailing List).

**Pull request merged**
